//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signup
    {
        public int FunEventId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
    
        public virtual FunEvent FunEvent { get; set; }
    }
}
