//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server.WebApi.WcfServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignupInput", Namespace="http://schemas.datacontract.org/2004/07/server.Data")]
    [System.SerializableAttribute()]
    public partial class SignupInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FunEventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FunEventId {
            get {
                return this.FunEventIdField;
            }
            set {
                if ((this.FunEventIdField.Equals(value) != true)) {
                    this.FunEventIdField = value;
                    this.RaisePropertyChanged("FunEventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractResult", Namespace="http://schemas.datacontract.org/2004/07/server.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(server.WebApi.WcfServiceReference.QueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(server.WebApi.WcfServiceReference.SignupResult))]
    public partial class AbstractResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private server.WebApi.WcfServiceReference.Error[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private server.WebApi.WcfServiceReference.OperationStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public server.WebApi.WcfServiceReference.Error[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public server.WebApi.WcfServiceReference.OperationStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://schemas.datacontract.org/2004/07/server.Data")]
    [System.SerializableAttribute()]
    public partial class QueryResult : server.WebApi.WcfServiceReference.AbstractResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private server.WebApi.WcfServiceReference.SignupRecord[] RecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public server.WebApi.WcfServiceReference.SignupRecord[] Records {
            get {
                return this.RecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordsField, value) != true)) {
                    this.RecordsField = value;
                    this.RaisePropertyChanged("Records");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignupResult", Namespace="http://schemas.datacontract.org/2004/07/server.Data")]
    [System.SerializableAttribute()]
    public partial class SignupResult : server.WebApi.WcfServiceReference.AbstractResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResourceIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceId {
            get {
                return this.ResourceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceIdField, value) != true)) {
                    this.ResourceIdField = value;
                    this.RaisePropertyChanged("ResourceId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/server.Data")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private server.WebApi.WcfServiceReference.ErrorType ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MembershipNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailError {
            get {
                return this.DetailErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailErrorField, value) != true)) {
                    this.DetailErrorField = value;
                    this.RaisePropertyChanged("DetailError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public server.WebApi.WcfServiceReference.ErrorType ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((this.ErrorTypeField.Equals(value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MembershipName {
            get {
                return this.MembershipNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MembershipNameField, value) != true)) {
                    this.MembershipNameField = value;
                    this.RaisePropertyChanged("MembershipName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationStatus", Namespace="http://schemas.datacontract.org/2004/07/server.Data")]
    public enum OperationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicatedWhenAdding = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorsWhenAdding = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DBError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoError = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorType", Namespace="http://schemas.datacontract.org/2004/07/server.Data")]
    public enum ErrorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyEntry = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataInvalid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessInvalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DBError = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignupRecord", Namespace="http://schemas.datacontract.org/2004/07/server.Data")]
    [System.SerializableAttribute()]
    public partial class SignupRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EventStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FunEventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunEventNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EventStartDate {
            get {
                return this.EventStartDateField;
            }
            set {
                if ((this.EventStartDateField.Equals(value) != true)) {
                    this.EventStartDateField = value;
                    this.RaisePropertyChanged("EventStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FunEventId {
            get {
                return this.FunEventIdField;
            }
            set {
                if ((this.FunEventIdField.Equals(value) != true)) {
                    this.FunEventIdField = value;
                    this.RaisePropertyChanged("FunEventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunEventName {
            get {
                return this.FunEventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FunEventNameField, value) != true)) {
                    this.FunEventNameField = value;
                    this.RaisePropertyChanged("FunEventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryInput", Namespace="http://schemas.datacontract.org/2004/07/server.Data")]
    [System.SerializableAttribute()]
    public partial class QueryInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FunEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FunEvent {
            get {
                return this.FunEventField;
            }
            set {
                if ((this.FunEventField.Equals(value) != true)) {
                    this.FunEventField = value;
                    this.RaisePropertyChanged("FunEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunnyEvent", Namespace="http://schemas.datacontract.org/2004/07/server.Data")]
    [System.SerializableAttribute()]
    public partial class FunnyEvent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EventStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FunEventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunEventNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EventStartDate {
            get {
                return this.EventStartDateField;
            }
            set {
                if ((this.EventStartDateField.Equals(value) != true)) {
                    this.EventStartDateField = value;
                    this.RaisePropertyChanged("EventStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FunEventId {
            get {
                return this.FunEventIdField;
            }
            set {
                if ((this.FunEventIdField.Equals(value) != true)) {
                    this.FunEventIdField = value;
                    this.RaisePropertyChanged("FunEventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunEventName {
            get {
                return this.FunEventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FunEventNameField, value) != true)) {
                    this.FunEventNameField = value;
                    this.RaisePropertyChanged("FunEventName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceReference.ISignUpService")]
    public interface ISignUpService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignup/Add", ReplyAction="http://tempuri.org/ISignup/AddResponse")]
        server.WebApi.WcfServiceReference.SignupResult Add(server.WebApi.WcfServiceReference.SignupInput signupInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignup/Add", ReplyAction="http://tempuri.org/ISignup/AddResponse")]
        System.Threading.Tasks.Task<server.WebApi.WcfServiceReference.SignupResult> AddAsync(server.WebApi.WcfServiceReference.SignupInput signupInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignup/Query", ReplyAction="http://tempuri.org/ISignup/QueryResponse")]
        server.WebApi.WcfServiceReference.QueryResult Query(server.WebApi.WcfServiceReference.QueryInput queryInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignup/Query", ReplyAction="http://tempuri.org/ISignup/QueryResponse")]
        System.Threading.Tasks.Task<server.WebApi.WcfServiceReference.QueryResult> QueryAsync(server.WebApi.WcfServiceReference.QueryInput queryInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunEvent/GetFutureEvents", ReplyAction="http://tempuri.org/IFunEvent/GetFutureEventsResponse")]
        server.WebApi.WcfServiceReference.FunnyEvent[] GetFutureEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunEvent/GetFutureEvents", ReplyAction="http://tempuri.org/IFunEvent/GetFutureEventsResponse")]
        System.Threading.Tasks.Task<server.WebApi.WcfServiceReference.FunnyEvent[]> GetFutureEventsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignUpServiceChannel : server.WebApi.WcfServiceReference.ISignUpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignUpServiceClient : System.ServiceModel.ClientBase<server.WebApi.WcfServiceReference.ISignUpService>, server.WebApi.WcfServiceReference.ISignUpService {
        
        public SignUpServiceClient() {
        }
        
        public SignUpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignUpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignUpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignUpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public server.WebApi.WcfServiceReference.SignupResult Add(server.WebApi.WcfServiceReference.SignupInput signupInput) {
            return base.Channel.Add(signupInput);
        }
        
        public System.Threading.Tasks.Task<server.WebApi.WcfServiceReference.SignupResult> AddAsync(server.WebApi.WcfServiceReference.SignupInput signupInput) {
            return base.Channel.AddAsync(signupInput);
        }
        
        public server.WebApi.WcfServiceReference.QueryResult Query(server.WebApi.WcfServiceReference.QueryInput queryInput) {
            return base.Channel.Query(queryInput);
        }
        
        public System.Threading.Tasks.Task<server.WebApi.WcfServiceReference.QueryResult> QueryAsync(server.WebApi.WcfServiceReference.QueryInput queryInput) {
            return base.Channel.QueryAsync(queryInput);
        }
        
        public server.WebApi.WcfServiceReference.FunnyEvent[] GetFutureEvents() {
            return base.Channel.GetFutureEvents();
        }
        
        public System.Threading.Tasks.Task<server.WebApi.WcfServiceReference.FunnyEvent[]> GetFutureEventsAsync() {
            return base.Channel.GetFutureEventsAsync();
        }
    }
}
